### PR TITLE
Issue/13

### PR DESCRIPTION
**Pull request by pogla**

### CODE REVIEW

**Comment by growdev** [comment]
@pogla 
There are a bunch of PHP notices due to the way that WC 3.0 wants order data to be accessed.

Please add version check and use new method if version 3.0 or greater.


```
[12-Mar-2018 19:42:34 UTC] PHP Notice:  order_total was called <strong>incorrectly</strong>. Order properties should not be accessed directly.
[12-Mar-2018 19:42:34 UTC] PHP Notice:  order_total was called <strong>incorrectly</strong>. Order properties should not be accessed directly.
[12-Mar-2018 19:42:34 UTC] PHP Notice:  billing_first_name was called <strong>incorrectly</strong>. Order properties should not be accessed directly.
[12-Mar-2018 19:42:34 UTC] PHP Notice:  billing_last_name was called <strong>incorrectly</strong>. Order properties should not be accessed directly.
[12-Mar-2018 19:42:34 UTC] PHP Notice:  id was called <strong>incorrectly</strong>. Order properties should not be accessed directly.
[12-Mar-2018 19:42:34 UTC] PHP Notice:  payment_method_title was called <strong>incorrectly</strong>. Order properties should not be accessed directly.
[12-Mar-2018 19:42:34 UTC] PHP Notice:  billing_first_name was called <strong>incorrectly</strong>. Order properties should not be accessed directly.
[12-Mar-2018 19:42:34 UTC] PHP Notice:  billing_last_name was called <strong>incorrectly</strong>. Order properties should not be accessed directly.
[12-Mar-2018 19:42:34 UTC] PHP Notice:  id was called <strong>incorrectly</strong>. Order properties should not be accessed directly.
[12-Mar-2018 19:42:34 UTC] PHP Notice:  payment_method_title was called <strong>incorrectly</strong>. Order properties should not be accessed directly.
```

**Comment by pogla** [comment]
@growdev I fixed the issues. Added wc 3 check and fixed the field descriptions:

screen shot 2018-03-12 at 22 52 30

**Comment by pogla** [comment]
Also, let me know if you'd like to change the descriptions texts.

**Comment by growdev** [comment]
@pogla I think this looks good!

**Pull request merged**
